### ISSUE TITLE
Dropped HMGs glow not distinct/obvious enough

### ISSUE THREAD

**Issue by ArturPhilibin** [xToken/CompMod#57]
I feel it is too similar to the coloring of an LMG and is often mistaking as one.
I took a look in [CompMod/lua/CompMod/Client/HeavyMachineGunAdjustments.lua](https://github.com/xToken/CompMod/blob/b90fe7aa2277f27c64361bf0465e5cd52e924df1/lua/CompMod/Client/HeavyMachineGunAdjustments.lua#L64) to see if I could spot  where it is set, but the only code I code figure was related was line #64 which seems to set the color of the ammo to red (I'm guessing in the comm/spec topdown view), could I make a change somewhere in here to also make the glow that same strong red?

**Comment by xToken** [comment]
HMGs will be red now, had to hex edit the model and make a couple other little tweaks.

**Comment by ArturPhilibin** [comment]
Cool thanks, would never have thought to look at the models

**Comment by ArturPhilibin** [comment]
Just saw this in game today and it works great, thanks for fix
